/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Scolarite;

import static Scolarite.PageDemandeInscriptionScolarite.date_inscription;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Date;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class PageDemandeInscriptionScolarite2 extends javax.swing.JFrame {
    private Connection conn = null;
    private Statement stmt = null;
    private ResultSet rs = null;
    
    /**
     * Creates new form PageDemandeInscriptionScolarite2
     */
    public PageDemandeInscriptionScolarite2() {
        initComponents();
        logouticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        logout = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Page des documents de l'etudiant");
        setMinimumSize(new java.awt.Dimension(722, 430));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(19, 68, 140));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Scolarite/user2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 47));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 26, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Service de scolarité");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 29, 158, 38));

        jButton1.setBackground(new java.awt.Color(19, 68, 140));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Accueil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, 210, 35));

        jButton2.setBackground(new java.awt.Color(19, 68, 140));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Les demandes d'inscriptions");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 182, 210, 35));

        jButton3.setBackground(new java.awt.Color(19, 68, 140));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Historique");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 235, 210, 35));

        logout.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 291, 30, 30));

        jButton4.setBackground(new java.awt.Color(19, 68, 140));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Déconnexion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 288, 210, 35));

        jButton5.setBackground(new java.awt.Color(19, 68, 140));
        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Les demandes d'inscriptions");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 182, 210, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 430));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(19, 68, 140));
        jButton6.setText("Carte Nationale");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 250, 40));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(19, 68, 140));
        jButton7.setText("Baccalauréat");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 250, 40));

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(19, 68, 140));
        jButton8.setText("Acte de naissance");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 250, 40));

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(19, 68, 140));
        jButton9.setText("Reçu de la préinscription");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 250, 40));

        jButton10.setBackground(new java.awt.Color(0, 153, 51));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton10.setText("Accepter");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 140, 40));

        jButton11.setBackground(new java.awt.Color(204, 0, 0));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton11.setText("Refuser");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 140, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void logouticon() {
        ImageIcon logoutt = new ImageIcon("src/logout-1.png");
        Image img = logoutt.getImage();
        Image imgScale = img.getScaledInstance(logout.getWidth(), logout.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon iconScale = new ImageIcon(imgScale);
        logout.setIcon(iconScale);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new PageAccueilScolarite().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        new PageDemandeInscriptionScolarite().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Historique().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new CarteNationale().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new Baccalauréat().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new ActeDeNaissance().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        new ReçuDePreinscription().setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // refuser
        //System.out.println(PageDemandeInscriptionScolarite.nom+" "+PageDemandeInscriptionScolarite.status);
                //enregister l'étudiant(e) dans l'historique avec état "refuser"
        try {
						Class.forName("com.mysql.cj.jdbc.Driver");
	 			    	Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetuml","root","");
	 					
	 		    	     String query = "insert into historique(nom,prenom,cin,date_inscription,status,etat)" + 
	 		    	             " values (?,?,?,?,?,?)";
	 		    	    PreparedStatement preparedStmt = conn.prepareStatement(query);
                                    
	 		              preparedStmt.setString(1,PageDemandeInscriptionScolarite.nom);
	 		    	      preparedStmt.setString(2,PageDemandeInscriptionScolarite.prenom);
	 		    	      preparedStmt.setString(3,PageDemandeInscriptionScolarite.cin);
                                      preparedStmt.setString(4,PageDemandeInscriptionScolarite.date_inscription);
	 		    	      preparedStmt.setString(5,PageDemandeInscriptionScolarite.status);
	 		    	      preparedStmt.setString(6,"refuser");
	 		    	
	 		    	       preparedStmt.execute();
	 		    	      
	 		    	      conn.close();

					}catch(Exception exce) {
	 		    	      JOptionPane.showMessageDialog(null,exce.getMessage(),"DEMANDE",JOptionPane.ERROR_MESSAGE);
                                      System.exit(0);
					}
        //rendre la collone traite "oui"
        try {
			   String nom,prenom,cin,status,date_inscription,etat;
			   
	    	   Class.forName("com.mysql.cj.jdbc.Driver");
	    	    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetuml","root","");
	    	     String query = "update inscriptions set traite = \"oui\" where etudiant_id = "+PageDemandeInscriptionScolarite.id+""; 
	 		    	             
	 		    	    PreparedStatement preparedStmt = conn.prepareStatement(query);
	 		    	         
	 		    	       preparedStmt.execute();
	 		    	      
	 		    	      
	            /*insert into etudiants(nom,prenom,code_apogee,cne,cin,adresse,numero_telephone,email,date_naissance,lieu_naissance,status,nom_prenom_mere,nom_prenom_pere,cin_pere,cin_mere,numero_telephone_pere,
                    numero_telephone_mere,ville,code_postal) values("x","y",55,"XYZ123","ABC456","d","+212uuu","ded","1111-11-11","dde","bachelier","a","b","d","e","+212rrr","+212yyyyyyy","tetouan",93040);*/
	            JOptionPane.showMessageDialog(null,"un(e) étudiant(e) à été refusé(e)!","INSCRIPTION",JOptionPane.INFORMATION_MESSAGE);
                    conn.close();
	      }catch(Exception e) {
	    	  System.out.println(e.getMessage());
	      }
        dispose();
        new PageDemandeInscriptionScolarite().setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // accepter
        //rendre la collone traite "oui"
         //enregister l'étudiant(e) dans l'historique avec état "accepter"
        try {
						Class.forName("com.mysql.cj.jdbc.Driver");
	 			    	Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetuml","root","");
	 					
	 		    	     String query = "insert into historique(nom,prenom,cin,date_inscription,status,etat)" + 
	 		    	             " values (?,?,?,?,?,?)";
	 		    	    PreparedStatement preparedStmt = conn.prepareStatement(query);
                                    
	 		              preparedStmt.setString(1,PageDemandeInscriptionScolarite.nom);
	 		    	      preparedStmt.setString(2,PageDemandeInscriptionScolarite.prenom);
	 		    	      preparedStmt.setString(3,PageDemandeInscriptionScolarite.cin);
                                       preparedStmt.setString(4,PageDemandeInscriptionScolarite.date_inscription);
                                      
                                      
	 		    	      preparedStmt.setString(5,PageDemandeInscriptionScolarite.status);
	 		    	      preparedStmt.setString(6,"accepter");
	 		    	
	 		    	       preparedStmt.execute();
	 		    	      
	 		    	      conn.close();

					}catch(Exception exce) {
	 		    	      JOptionPane.showMessageDialog(null,exce.getMessage(),"DEMANDE",JOptionPane.ERROR_MESSAGE);
					System.exit(0);
                                        }
        try {
			   
			   
	    	   Class.forName("com.mysql.cj.jdbc.Driver");
	    	    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetuml","root","");
	    	     String query = "update inscriptions set traite = \"oui\" where etudiant_id = "+PageDemandeInscriptionScolarite.id+""; 
	 		    	             
	 		    	    PreparedStatement preparedStmt = conn.prepareStatement(query);
	 		    	         
	 		    	       preparedStmt.execute();
	 		    	      
	 		  JOptionPane.showMessageDialog(null,"un(e) étudiant(e) à été accepté(e)!","INSCRIPTION",JOptionPane.INFORMATION_MESSAGE);

	            /*insert into etudiants(nom,prenom,code_apogee,cne,cin,adresse,numero_telephone,email,date_naissance,lieu_naissance,status,nom_prenom_mere,nom_prenom_pere,cin_pere,cin_mere,numero_telephone_pere,
                    numero_telephone_mere,ville,code_postal) values("x","y",55,"XYZ123","ABC456","d","+212uuu","ded","1111-11-11","dde","bachelier","a","b","d","e","+212rrr","+212yyyyyyy","tetouan",93040);*/
                    conn.close();
	      }catch(Exception e) {
	    	  System.out.println(e.getMessage());
	      }


        // PageDemandeInscriptionScolarite.model.removeRow(PageDemandeInscriptionScolarite.rowSelected);
        dispose();
        new PageDemandeInscriptionScolarite().setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/icon.png");
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageDemandeInscriptionScolarite2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageDemandeInscriptionScolarite2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageDemandeInscriptionScolarite2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageDemandeInscriptionScolarite2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageDemandeInscriptionScolarite2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logout;
    // End of variables declaration//GEN-END:variables
}
