/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Scolarite;
import Apogée.*;
import EnseignantChercheur.*;
import RespoCommision.PageAccueilRespoCommi;
import RespoFormDocto.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author hp
 */
public class PageLogin extends javax.swing.JFrame {
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    public static String email_enseignant_charcheur = "";
    /**
     * Creates new form PageLoginDeServiceDeScolarite
     */
    public PageLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Page d'authentification");
        setBackground(new java.awt.Color(239, 239, 239));
        setMinimumSize(new java.awt.Dimension(722, 430));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Scolarite/ENSA-Tétouan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 90, 100));

        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText("Entrez votre email");
        jTextField2.setName(""); // NOI18N
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 260, 40));

        jButton1.setBackground(new java.awt.Color(19, 68, 140));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log in");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 100, 40));

        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 260, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Email :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 50, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Mot de passe :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 90, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        // TODO add your handling code here:
        if(jTextField2.getText().equals("Entrez votre email")) {
            jTextField2.setText("");
            jTextField2.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        if(jTextField2.getText().equals("")) {
            jTextField2.setText("Entrez votre email");
            jTextField2.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // LOG IN
        	int compteur = 0;
        String email = jTextField2.getText(),prenom,nom;
        String text = email.split("@")[0];
			 	            
	prenom = text.split("\\.")[0];
	nom = text.split("\\.")[1];
        
        String type = "";
        try {
			    	  Class.forName("com.mysql.cj.jdbc.Driver");
                     conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetuml","root","");
                     stmt = conn.createStatement(); 
                     rs = stmt.executeQuery("SELECT * FROM authentification");

			            while(rs.next()) {
			            	//System.out.println(rs.getInt(1)+" "+rs.getString(2)+" "+rs.getString(3));
			            	if(rs.getString(2).equals(jTextField2.getText()) && rs.getString(3).equals(jPasswordField1.getText())) {
			            		compteur ++;
                                                type = rs.getString(4);
			            	}
			            }
			            if(compteur == 1){
                                        if(type.equals("scolarité")){
			                   dispose();
                                           new PageAccueilScolarite().setVisible(true);  
                                           JOptionPane.showMessageDialog(null,"Bienvenue "+nom+" "+prenom+" !","AUTHENTIFICATION",JOptionPane.INFORMATION_MESSAGE);
                                        }
                                        else if(type.equals("apogée")){
			                   dispose();
                                           new PageAcceuilApogee().setVisible(true);
                                           JOptionPane.showMessageDialog(null,"Bienvenue "+nom+" "+prenom+" !","AUTHENTIFICATION",JOptionPane.INFORMATION_MESSAGE);
                                        }
                                        else if(type.equals("enseignant-chercheur")){
                                            email_enseignant_charcheur = jTextField2.getText();
			                   dispose();
                                           new PageAccueilEnseignant().setVisible(true);
                                           JOptionPane.showMessageDialog(null,"Bienvenue "+nom+" "+prenom+" !","AUTHENTIFICATION",JOptionPane.INFORMATION_MESSAGE);
                                        }
                                        else if(type.equals("formation-continue")){
			                   dispose();
                                           new PageAccueilRespo().setVisible(true);
                                           JOptionPane.showMessageDialog(null,"Bienvenue "+nom+" "+prenom+" !","AUTHENTIFICATION",JOptionPane.INFORMATION_MESSAGE);
                                        }
                                        else if(type.equals("Responsable-Commision")){
			                   dispose();
                                           new PageAccueilRespoCommi().setVisible(true);
                                           JOptionPane.showMessageDialog(null,"Bienvenue "+nom+" "+prenom+" !","AUTHENTIFICATION",JOptionPane.INFORMATION_MESSAGE);
                                        }
                                        
			            }else {
			            	JOptionPane.showMessageDialog(null,"email ou mot de passe est invalide","AUTHENTIFICATION",JOptionPane.ERROR_MESSAGE);
			            	jTextField2.setText("");
                                        jPasswordField1.setText("");
			            }
			            	
			      }catch(Exception exc) {
			            	JOptionPane.showMessageDialog(null,exc.getMessage(),"SQL",JOptionPane.ERROR_MESSAGE);
			      }  

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/icon.png");
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
