/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Scolarite;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author hp
 */
public class PageDemandeInscriptionScolarite extends javax.swing.JFrame {
    private Connection conn = null;
    private Statement stmt = null;
    private ResultSet rs = null;
    private Connection conn1 = null;
    private Statement stmt1 = null;
    private ResultSet rs1 = null;
    
    
    
    
    
    
    
    
    
    
    
    public static DefaultTableModel model = null;
    public static int id ;
    public static int rowSelected ;
    int compteur = 0;
    public static String nom ="";
    public static String prenom ="";
    public static String cin ="";
    public static String date_inscription ="";
    public static String status ="";



    /**
     * Creates new form PageDemandeInscriptionScolarite
     */
    public PageDemandeInscriptionScolarite() {
        initComponents();
        logouticon();
        JTableHeader theader = jTable1.getTableHeader();
        theader.setBackground(Color.blue);
        try {
			
			    model = (DefaultTableModel)jTable1.getModel();
			   String nom,prenom,cin,status,date_inscription;
			   
	    	   Class.forName("com.mysql.cj.jdbc.Driver");
	    	    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetuml","root","");
	    	    stmt = conn.createStatement();
	    	    rs = stmt.executeQuery("SELECT nom,prenom,cin,status,date_inscription,id FROM etudiants");
	            while(rs.next()) {
                                 conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetuml","root","");
                                 stmt1 = conn1.createStatement();
                                 rs1 = stmt1.executeQuery("SELECT traite FROM inscriptions where etudiant_id = "+rs.getInt(6));
	            	 nom = rs.getString(1);
	            	prenom = rs.getString(2);
	            	cin = rs.getString(3);
	            	status = rs.getString(4);
	            	date_inscription = rs.getString(5);
                                 while(rs1.next()){
                            if(rs1.getString(1).equals("non")){
                        compteur ++;
	            	model.addRow(new Object[] {nom,prenom,cin,date_inscription,status});
                            }
                            
                        }
                        
	            }
                    conn1.close();
                    conn.close();
	      }catch(Exception e) {
	    	  System.out.println(e.getMessage());
	      }
       jLabel4.setText(compteur+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        logout = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Page de liste des demandes d'inscription");
        setMinimumSize(new java.awt.Dimension(722, 430));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(19, 68, 140));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Scolarite/user2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 47));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 26, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Service de scolarité");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 29, 158, 38));

        jButton1.setBackground(new java.awt.Color(19, 68, 140));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Accueil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, 210, 35));

        jButton2.setBackground(new java.awt.Color(19, 68, 140));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Les demandes d'inscriptions");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 182, 210, 35));

        jButton3.setBackground(new java.awt.Color(19, 68, 140));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Historique");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 235, 210, 35));

        logout.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 291, 30, 30));

        jButton4.setBackground(new java.awt.Color(19, 68, 140));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Déconnexion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 288, 210, 35));

        jButton5.setBackground(new java.awt.Color(19, 68, 140));
        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Les demandes d'inscriptions");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 182, 210, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 430));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Préom", "CIN / Passport", "Date d'inscription", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setGridColor(new java.awt.Color(19, 68, 140));
        jTable1.setMinimumSize(new java.awt.Dimension(235, 0));
        jTable1.setPreferredSize(new java.awt.Dimension(415, 320));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setMinWidth(85);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(85);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(85);
            jTable1.getColumnModel().getColumn(3).setMinWidth(105);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(105);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(105);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 460, 300));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(19, 68, 140));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre de demande actuel : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 16, 200, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(19, 68, 140));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("0");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 16, 50, 30));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(19, 68, 140));
        jButton6.setText("Consulter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 140, 40));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(19, 68, 140));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bachelier", "Etudiant CNC" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox1MouseReleased(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox1KeyReleased(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 16, 160, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void logouticon() {
        ImageIcon logoutt = new ImageIcon("src/logout-1.png");
        Image img = logoutt.getImage();
        Image imgScale = img.getScaledInstance(logout.getWidth(), logout.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon iconScale = new ImageIcon(imgScale);
        logout.setIcon(iconScale);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new PageAccueilScolarite().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Historique().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        new PageLogin().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // consulter
        rowSelected = jTable1.getSelectedRow();
        if(jTable1.getSelectedRow() >= 0){
            nom = model.getValueAt(jTable1.getSelectedRow(), 0).toString();
            prenom = model.getValueAt(jTable1.getSelectedRow(), 1).toString();
             cin = model.getValueAt(jTable1.getSelectedRow(), 2).toString();
             date_inscription = model.getValueAt(jTable1.getSelectedRow(), 3).toString();
             
             status = model.getValueAt(jTable1.getSelectedRow(), 4).toString();
            try {
	    	   Class.forName("com.mysql.cj.jdbc.Driver");
	    	    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetuml","root","");
	    	    stmt = conn.createStatement();
	    	    rs = stmt.executeQuery("SELECT id FROM etudiants where cin = '"+cin+"'");
	            if(rs.next()) {
	            	id = rs.getInt(1);
	            }
                    conn.close();
	      }catch(Exception e) {
	    	  System.out.println(e.getMessage());
	      }
            dispose();
        new PageDemandeInscriptionScolarite2().setVisible(true);
        }else{
           JOptionPane.showMessageDialog(null,"aucune ligne n'est séléctioné","ligne(s) non selectionés",JOptionPane.ERROR_MESSAGE);	
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseReleased

    }//GEN-LAST:event_jComboBox1MouseReleased

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // mouse clicked
        
                model.setRowCount(0);
        if(jComboBox1.getSelectedItem().toString().equals("Bachelier")){
            int compteur1 = 0;
            try {
			
			   DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
			   String nom,prenom,cin,status,date_inscription;
			   
	    	   Class.forName("com.mysql.cj.jdbc.Driver");
	    	    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetuml","root","");
	    	    stmt = conn.createStatement();
	    	    rs = stmt.executeQuery("SELECT nom,prenom,cin,status,date_inscription,id FROM etudiants where status = \"bachelier\"");
	            while(rs.next()) {
	            	 conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetuml","root","");
                                 stmt1 = conn1.createStatement();
                                 rs1 = stmt1.executeQuery("SELECT traite FROM inscriptions where etudiant_id = "+rs.getInt(6));
	            	while(rs1.next()){
                            if(rs1.getString(1).equals("non")){
                                nom = rs.getString(1);
	            	prenom = rs.getString(2);
	            	cin = rs.getString(3);
	            	status = rs.getString(4);
	            	date_inscription = rs.getString(5);
                        compteur1 ++;
	            	model.addRow(new Object[] {nom,prenom,cin,date_inscription,status});
                            }
                            
                        }
                        
	            }/*insert into etudiants(nom,prenom,code_apogee,cne,cin,adresse,numero_telephone,email,date_naissance,lieu_naissance,status,nom_prenom_mere,nom_prenom_pere,cin_pere,cin_mere,numero_telephone_pere,
                    numero_telephone_mere,ville,code_postal) values("x","y",55,"XYZ123","ABC456","d","+212uuu","ded","1111-11-11","dde","bachelier","a","b","d","e","+212rrr","+212yyyyyyy","tetouan",93040);*/
	            conn1.close();
                    conn.close();
	      }catch(Exception e) {
	    	  System.out.println(e.getMessage());
	      }
            jLabel4.setText(compteur1+"");
        }else if(jComboBox1.getSelectedItem().toString().equals("Etudiant CNC")){
            int compteur2 = 0;
            try {
			
			   DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
			   String nom,prenom,cin,status,date_inscription;
			   
	    	   Class.forName("com.mysql.cj.jdbc.Driver");
	    	    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetuml","root","");
	    	    stmt = conn.createStatement();
	    	    rs = stmt.executeQuery("SELECT nom,prenom,cin,status,date_inscription,id FROM etudiants where status = \"etudiantcnc\"");
	            while(rs.next()) {
	            	 conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetuml","root","");
                                 stmt1 = conn1.createStatement();
                                 rs1 = stmt1.executeQuery("SELECT traite FROM inscriptions where etudiant_id = "+rs.getInt(6));
	            	while(rs1.next()){
                            if(rs1.getString(1).equals("non")){
                                nom = rs.getString(1);
	            	prenom = rs.getString(2);
	            	cin = rs.getString(3);
	            	status = rs.getString(4);
	            	date_inscription = rs.getString(5);
                        compteur2 ++;
	            	model.addRow(new Object[] {nom,prenom,cin,date_inscription,status});
                            }
                            
                        }
                        
	            }/*insert into etudiants(nom,prenom,code_apogee,cne,cin,adresse,numero_telephone,email,date_naissance,lieu_naissance,status,nom_prenom_mere,nom_prenom_pere,cin_pere,cin_mere,numero_telephone_pere,
                    numero_telephone_mere,ville,code_postal) values("x","y",55,"XYZ123","ABC456","d","+212uuu","ded","1111-11-11","dde","bachelier","a","b","d","e","+212rrr","+212yyyyyyy","tetouan",93040);*/
	            conn.close();
	      }catch(Exception e) {
	    	  System.out.println(e.getMessage());
	      }
            jLabel4.setText(compteur2+"");
        }
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed

    }//GEN-LAST:event_jComboBox1MousePressed

    private void jComboBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1MouseEntered

    private void jComboBox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1KeyReleased

    private void jComboBox1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/icon.png");
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageDemandeInscriptionScolarite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageDemandeInscriptionScolarite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageDemandeInscriptionScolarite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageDemandeInscriptionScolarite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageDemandeInscriptionScolarite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logout;
    // End of variables declaration//GEN-END:variables
}
