/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RespoCommision;

import Scolarite.PageDemandeInscriptionScolarite;
import static Scolarite.PageDemandeInscriptionScolarite.cin;
import static Scolarite.PageDemandeInscriptionScolarite.date_inscription;
import static Scolarite.PageDemandeInscriptionScolarite.id;
import static Scolarite.PageDemandeInscriptionScolarite.model;
import static Scolarite.PageDemandeInscriptionScolarite.nom;
import static Scolarite.PageDemandeInscriptionScolarite.prenom;
import static Scolarite.PageDemandeInscriptionScolarite.status;
import Scolarite.PageDemandeInscriptionScolarite2;
import Scolarite.PageLogin;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class PageListeDesCandidatsFS extends javax.swing.JFrame {
    private Connection conn = null;
    private Connection conn1 = null;
    private Statement stmt = null;
    private ResultSet rs = null;
    private Statement stmt1 = null;
    private ResultSet rs1 = null;
    private DefaultTableModel model = null;
    /**
     * Creates new form PageListeDesCandidatsFS
     */
    public PageListeDesCandidatsFS() {
        initComponents();
        logouticon();
        try {
			
			    model = (DefaultTableModel)jTable1.getModel();
			   String nom,prenom,cin,email,filiere;
			  
	    	   Class.forName("com.mysql.cj.jdbc.Driver");
	    	    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetuml","root","");
	    	    stmt = conn.createStatement();
	    	    rs = stmt.executeQuery("SELECT etudiant_id FROM candidatures where etat_candidature = \"non\" ");
	            while(rs.next()) {
                      conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetuml","root","");
                        stmt1 = conn1.createStatement();
	    	    rs1 = stmt1.executeQuery("SELECT nom,prenom,cin,email,filiere FROM etudiants where id ="+rs.getInt(1));
	              while(rs1.next()){
                          nom = rs1.getString(1);
	            	prenom = rs1.getString(2);
	            	cin = rs1.getString(3);
                        email = rs1.getString(5);
	            	filiere = rs1.getString(4);
                        model.addRow(new Object[] {nom,prenom,cin,email,filiere});
                      }
	            	
	            	
	            }/*insert into etudiants(nom,prenom,code_apogee,cne,cin,adresse,numero_telephone,email,date_naissance,lieu_naissance,status,nom_prenom_mere,nom_prenom_pere,cin_pere,cin_mere,numero_telephone_pere,
                    numero_telephone_mere,ville,code_postal) values("x","y",55,"XYZ123","ABC456","d","+212uuu","ded","1111-11-11","dde","bachelier","a","b","d","e","+212rrr","+212yyyyyyy","tetouan",93040);*/
	            conn1.close();
                    conn.close();
	      }catch(Exception e) {
	    	  System.out.println(e.getMessage());
	      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        logout = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Page de liste des candidats FS");
        setMinimumSize(new java.awt.Dimension(740, 430));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(19, 68, 140));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Scolarite/user2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 47));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 26, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Responsable Commision");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 180, 38));

        jButton1.setBackground(new java.awt.Color(19, 68, 140));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Accueil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, 210, 35));

        jButton2.setBackground(new java.awt.Color(19, 68, 140));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Liste des candidats");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 182, 210, 35));

        jButton3.setBackground(new java.awt.Color(19, 68, 140));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Historique");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 235, 210, 35));

        logout.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 291, 30, 30));

        jButton4.setBackground(new java.awt.Color(19, 68, 140));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Déconnexion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 288, 210, 35));

        jButton5.setBackground(new java.awt.Color(19, 68, 140));
        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Les demandes d'inscriptions");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 182, 210, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 430));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(19, 68, 140));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Liste des candidats de la faculté des sciences :");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(19, 68, 140)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 420, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prénom", "CIN", "Filière", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 460, 250));

        jButton11.setBackground(new java.awt.Color(204, 0, 0));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton11.setText("Refuser");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 140, 40));

        jButton10.setBackground(new java.awt.Color(0, 153, 51));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton10.setText("Accepter");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 140, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void logouticon() {
        ImageIcon logoutt = new ImageIcon("src/logout-1.png");
        Image img = logoutt.getImage();
        Image imgScale = img.getScaledInstance(logout.getWidth(), logout.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon iconScale = new ImageIcon(imgScale);
        logout.setIcon(iconScale);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new PageAccueilRespoCommi().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new PageHistoriqueRespoCommi().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        new PageLogin().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
    if(jTable1.getSelectedRow() >= 0){
        try {
			   
			   String CIN= jTable1.getValueAt(jTable1.getSelectedRow(),2).toString() ;
                           int id = 0;
                            Class.forName("com.mysql.cj.jdbc.Driver");
	    	    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetuml","root","");
	    	    stmt = conn.createStatement();
	    	    rs = stmt.executeQuery("SELECT id FROM etudiants where cin = '"+CIN+"'");
                    while(rs.next()){
                        id = rs.getInt(1);
                    }
	    	   Class.forName("vcom.mysql.cj.jdbc.Driver");
	    	    conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetuml","root","");
	    	     String query = "update candidatures set etat_candidature = \"oui\" , type = \"refuser\" where etudiant_id = "+id; 
	 		    	             
	 		    	    PreparedStatement preparedStmt = conn1.prepareStatement(query);
	 		    	         
	 		    	       preparedStmt.execute();
	 		    	      
	 		  JOptionPane.showMessageDialog(null,"un(e) étudiant(e) à été refusé(e)!","INSCRIPTION-FS",JOptionPane.INFORMATION_MESSAGE);
                          dispose();
                          new PageListeDesCandidatsFS().setVisible(true);
	            /*insert into etudiants(nom,prenom,code_apogee,cne,cin,adresse,numero_telephone,email,date_naissance,lieu_naissance,status,nom_prenom_mere,nom_prenom_pere,cin_pere,cin_mere,numero_telephone_pere,
                    numero_telephone_mere,ville,code_postal) values("x","y",55,"XYZ123","ABC456","d","+212uuu","ded","1111-11-11","dde","bachelier","a","b","d","e","+212rrr","+212yyyyyyy","tetouan",93040);*/
                    conn1.close();
                    conn.close();
	      }catch(Exception e) {
	    	  System.out.println(e.getMessage());
	      }
        }else{
           JOptionPane.showMessageDialog(null,"aucune ligne n'est séléctioné","ligne(s) non selectionés",JOptionPane.ERROR_MESSAGE);	
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      if(jTable1.getSelectedRow() >= 0){
        try {
			   
			   String CIN= jTable1.getValueAt(jTable1.getSelectedRow(),2).toString() ;
                           int id = 0;
                            Class.forName("com.mysql.cj.jdbc.Driver");
	    	    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetuml","root","");
	    	    stmt = conn.createStatement();
	    	    rs = stmt.executeQuery("SELECT id FROM etudiants where cin = '"+CIN+"'");
                    while(rs.next()){
                        id = rs.getInt(1);
                    }
	    	   Class.forName("com.mysql.cj.jdbc.Driver");
	    	    conn1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/projetuml","root","");
	    	     String query = "update candidatures set etat_candidature = \"oui\" , type = \"accepter\" where etudiant_id = "+id; 
	 		    	             
	 		    	    PreparedStatement preparedStmt = conn1.prepareStatement(query);
	 		    	         
	 		    	       preparedStmt.execute();
	 		    	      
	 		  JOptionPane.showMessageDialog(null,"un(e) étudiant(e) à été accepté(e)!","INSCRIPTION-FS",JOptionPane.INFORMATION_MESSAGE);
                          dispose();
                          new PageListeDesCandidatsFS().setVisible(true);
	            /*insert into etudiants(nom,prenom,code_apogee,cne,cin,adresse,numero_telephone,email,date_naissance,lieu_naissance,status,nom_prenom_mere,nom_prenom_pere,cin_pere,cin_mere,numero_telephone_pere,
                    numero_telephone_mere,ville,code_postal) values("x","y",55,"XYZ123","ABC456","d","+212uuu","ded","1111-11-11","dde","bachelier","a","b","d","e","+212rrr","+212yyyyyyy","tetouan",93040);*/
                    conn1.close();
                    conn.close();
	      }catch(Exception e) {
	    	  System.out.println(e.getMessage());
	      }
        }else{
           JOptionPane.showMessageDialog(null,"aucune ligne n'est séléctioné","ligne(s) non selectionés",JOptionPane.ERROR_MESSAGE);	
        }
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/icon.png");
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageListeDesCandidatsFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageListeDesCandidatsFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageListeDesCandidatsFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageListeDesCandidatsFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageListeDesCandidatsFS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logout;
    // End of variables declaration//GEN-END:variables
}
